version: "3.7"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - network

  spring-boot-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - network

networks:
  network:
